### ISSUE TITLE
Weird function behaviour in objects

### ISSUE THREAD

**Issue by poisson-myfish** [sebbekarlsson/hermes#130]
So I was playing with Hermes, and I wrote this code:

```c#
void say(string what) {
    print(what);
}

for (int i = 0; i < 11; i += 1) {
    say(i);
}

object Person = {
    string name;

    void Init(string n) {
        this.name = n;
    }

    string GetName() {
        return this.name;
    }
};

Person p;
p.Init("Bob");
print(p.GetName());
```

Weirdly though, when I run it I get this error:
```[Line 16] Unexpected token `string`, was expecting `9`.```

I looked over my code a dozen times, and I don't seem to be doing anything wrong. Is this a bug?

System:
- Debian 10 stable
- Unmodified version of Hermes, updated 10 minutes before writing this

**Comment by sebbekarlsson** [comment]
@poisson-myfish  Hello! This is indeed a bug, and thanks for pointing it out.

Here is an example where it actually runs:
```C
void say(string what) {
    print(what);
}

for (int i = 0; i < 11; i += 1) {
    say(i);
}

object Person = {
    string name;

    void Init(string n) {
        this.name = n;
    };

    string GetName() {
        return this.name;
    }
};

object createPerson() {
    return new Person;
}

object p = createPerson();
p.Init("Bob");
print(p.GetName());
```

The main problem is the missing semi colon after the `Init` function declaration, after the curly brace.
Semi colons shouldn't be required however, so this is indeed a bug.

**Comment by poisson-myfish** [comment]
@sebbekarlsson Glad to help!
