### ISSUE TITLE
Show line number in error messages

### ISSUE THREAD

**Issue by sebbekarlsson** [sebbekarlsson/hermes#45]

**Comment by jay51** [comment]
is this issue still open, it seems that you've already implemented this for the most part

**Comment by sebbekarlsson** [comment]
@jay51  The issue is still open!
I see that you added line numbers to the error messages within the lexer, thank you for the contribution! Thats great :dancer:  I am going to look into merging it.

However, the error messages within the runtime (visitor) still lacks line numbers,
and I think it might be a bit tricky to get it to work because one does not have access to the line number at that point.
This is because the AST has already been created and the information about the data from the lexer is gone.

One way to solve it could possibly be to store the line numbers on the AST nodes so that one can access them while doing the "visit operations" inside the runtime.

**Comment by sebbekarlsson** [comment]
Closing this thanks to @jay51
