### ISSUE TITLE
double free in hello_world.he example

### ISSUE THREAD

**Issue by jay51** [sebbekarlsson/hermes#52]
I used the make file to build and ran `./hermes.out examples/hello_world.he`
I'm running `Fedora 31 workstation`
![terminal image](https://imgur.com/XAFuYyC.png)

**Comment by sebbekarlsson** [comment]
Hey!
Thank you. That was embarrassing... It is fixed now.
https://github.com/sebbekarlsson/hermes/commit/d93e273c20ed48afac3db9e2abc90de2bf2e46e4

Thank you for contributing :)
