### ISSUE TITLE
Add a hermes language grammar file

### ISSUE THREAD

**Issue by jay51** [sebbekarlsson/hermes#79]
I can read the `src/hermes_parser.c` but It would be nice to have a language grammar file to refer to when confused.

**Comment by jay51** [comment]
I'm really not good at this but I tried to make a simple grammar file that looks like this. still not sure if this is correct?
```c
hermes_parser_parse
""" statements: compound_statement """


hermes_parser_parse_statements
""" compound_statement: statement* """


hermes_parser_parse_statement
""" statement: TOKEN_ID
            | TOKEN_NUMBER_VALUE
            | TOKEN_CHAR_VALUE
            | TOKEN_FLOAT_VALUE
            | TOKEN_NUMBER_VALUE
            | TOKEN_INTEGER_VALUE
            | EMTPY (NOOP)
"""


hermes_parser_parse_expr
""" expr : term ((PLUS | MINUS) term)* """



hermes_parser_parse_term
""" term: function_definition
        | factor ((TOKEN_DIV
        | TOKEN_STAR
        | TOKEN_AND
        | TOKEN_LESS_THAN
        | TOKEN_LARGER_THAN
        | TOKEN_EQUALS_EQUALS
        | TOKEN_NOT_EQUALS) factor)*
"""


`hermes_parser_parse_factor`
""" factor: VALUE_FALSE
        | VALUE_TRUE
        | VALUE_NULL
        | STATEMENT_NEW
        | VARIABLE
        | TOKEN_DOT factor
        | TOKEN_LBRACKET expr TOKEN_RBRACKET
        | TOKEN_NUMBER_VALUE
        | TOKEN_INTEGER_VALUE
        | TOKEN_FLOAT_VALUE
        | TOKEN_STRING_VALUE
        | TOKEN_CHAR_VALUE
"""
```

**Comment by sebbekarlsson** [comment]
@jay51  Great idea!
I think it looks good. However, I have never worked with grammar files either so I don't really know how it _should_ look.
I trust you though, it looks good and it's a great idea.

Is it possible to auto-generate it or does one have to keep updating it every time a change in the parser is made?

**Comment by jay51** [comment]
I'm new to this too, I used the python [grammar specification](https://docs.python.org/3/reference/grammar.html)  and [javascript](https://btmills.github.io/parserapi/#Statement) as a reference.

I'm not sure if it's possible to auto generate this however I will continue working on this to see how far I can go.

**Comment by sebbekarlsson** [comment]
closing since grammar file was added
