### ISSUE TITLE
what's the purpose of the if statement here?

### ISSUE THREAD

**Issue by jay51** [sebbekarlsson/hermes#81]
https://github.com/sebbekarlsson/hermes/blob/0683245c19b4ebe8e7d5d91e2745875177b17dc0/src/hermes_parser.c#L611

It seems that the `if (hermes_parser->current_token->type == TOKEN_ID)` was left there by mistake. I tried to remove it and ran the test and it seems to be working fine without it.

**Comment by sebbekarlsson** [comment]
@jay51 this is for consuming the "if" token before the left parantheses.
It's possible that in some cases the code works without it but removing it is not the right solution, it would probably cause undefined behavior.

But yes it is a bit difficult to see why it is there, maybe I should write a comment or something.

If I'm not mistaken, there currently dont exist any tests for if-statements. That's probably why the tests were succeeding haha

**Comment by sebbekarlsson** [comment]
I am closing this issue.
I tried removing it and the `if` test is failing with the message:

[Line 4] Unexpected token `if`, was expecting `8`.
