### ISSUE TITLE
implement else statement 

### ISSUE THREAD

**Issue by jay51** [sebbekarlsson/hermes#86]
as of now the else statement doesn't work.
```c
int i = 0;

if (i == 1){
    print("it's 1");

} else if (i != 0) {
    print("it's not 1");

} else {
    print("it's not");
}

print("hello world");
```

**Comment by sebbekarlsson** [comment]
Are you sure?
The code in your example execute fine for me.
Output:
```
it's not
hello world
```

**Comment by jay51** [comment]
yes, I just tested it. have you made any changes to the code. what branch are you on?

**Comment by sebbekarlsson** [comment]
I am on master!
For me, this has always worked, I have not made any changes

**Comment by sebbekarlsson** [comment]
I will add a test for it as well, so that githubs test system can validate it as well

**Comment by jay51** [comment]
I worked on the else statement just now and I implemented it. not sure if you want to me to make a pull request

**Comment by sebbekarlsson** [comment]
@jay51 
Here you can see a test from github validating that it already works:
https://github.com/sebbekarlsson/hermes/pull/87/checks?check_run_id=535776639

@jay51 
But make a PR and I can look at what you did

**Comment by jay51** [comment]
yup just tested it. the `else` works. but that's very weird  because it didn't work for me earlier

**Comment by sebbekarlsson** [comment]
@jay51 I merged your stuff, even though else still worked for me.
But your code makes more sense I think, so great job!
