### ISSUE TITLE
Create syntax highlighting for popular editors

### ISSUE THREAD

**Issue by sebbekarlsson** [sebbekarlsson/hermes#89]
One way to make more people interested in Hermes would be to create syntax highlighting for
popular editors such as:

* vim
* emacs
* VSCode
* sublime

... etc

**Comment by jay51** [comment]
I use python syntax highlighting with hermes in vim `set ft=python` and it works great for the most part. 
python syntax highlighting works pretty well with hermes syntax. maybe we could use that.

**Comment by sebbekarlsson** [comment]
@jay51  Great idea! Or possibly use the python syntax file as a base and create a custom one from that

**Comment by sebbekarlsson** [comment]
https://github.com/sebbekarlsson/hermes-vim
